DefaultContentLanguage = "es"
baseURL = "https://tucurrique.go.cr/"
disqusShortname = ""
enableRobotsTXT = true
googleAnalytics = ""
theme = "bilberry-hugo-theme"
title = "Concejo Municipal de Tucurrique"
[Languages.es]
weight = 1
[blackfriday]
hrefTargetBlank = false
[markup.tableOfContents]
endLevel = 5
ordered = false
startLevel = 2
staticDir = ["static"]
[outputs]
home = ["HTML", "JSON", "RSS"]
page = ["HTML"]
[params]
algolia_apiKey = "16030625f1a4d0dd3b8aefd794fd4cf1"
algolia_appId = "45CEN6X6AT"
algolia_currentLanguageOnly = true
algolia_indexName = "bilberry-hugo-theme"
algolia_search = false
amountCategoriesInFooter = 7
amountLatestPostsInFooter = 7
author = "Tucurrique"
avatarEmail = "info@tucurrique.go.cr"
commentoJsURL = "https://commento.lednerb.de/js/commento.js"
copyrightBy = "Concejo Municipal de Tucurrique"
copyrightUrl = "/"
copyrightUseCurrentYear = true
creditsText = "Trabajamos para servirle"
creditsUrl = "/"
css_modules = []
customImage = ""
dateFormat = "2006-01-02"
description = "Sitio oficial del Concejo Municipal de Tucurrique"
enableMomentJs = true
enable_mathjax = false
js_modules = []
keywords = "local government,costa rica,tucurrique"
overlayIcon = "fa-home"
paginate = 7
permanentTopNav = true
resizeImages = true
showFooter = true
showFooterLanguageChooser = true
showHeaderLanguageChooser = true
showReadingTime = false
showSocialMedia = true
stickyNav = false
subtitle = "Trabajamos para servirle"
tocMinWordCount = 400
[[params.socialMediaLinks]]
icon = "fab fa-facebook-square"
link = "https://www.facebook.com/tucurrique.go.cr/"
[[params.socialMediaLinks]]
icon = "fab fa-instagram-square"
link = "https://www.instagram.com/tucurriquegocr/"
[[params.socialMediaLinks]]
icon = "fab fa-twitter-square"
link = "https://twitter.com/tucurriquegocr"
[taxonomies]
author = "author"
category = "categories"
series = "series"
tag = "tags"
